routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('test');

Route::post('/cart/add', 'CartController@create')->name('cart.add');
Route::patch('/cart/update/{id}', 'CartController@update')->name('cart.update');
Route::delete('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart', 'CartController@show')->name('cart.index');

Route::get('/checkout', 'CheckoutController@index')->name('checkout');
Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

Route::get('/p/{slug}', 'ProductController@show');
Route::get('/c/{slug?}', 'CategoryController@show')->name('category.menu');

Route::post('/r/comments', 'CommentController@store')->name('comments.store');

Route::middleware('auth')->group(function () {
    Route::get('/u/profile', 'UserController@edit');
    Route::patch('/u/profile', 'UserController@update')->name('user.update');
});

Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin.index');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions', 'Admin\PermissionController')->except(['show']);
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController')->except(['show']);
    Route::resource('products', 'Admin\ProductController');
    Route::resource('download', 'Admin\DownloadController')->only(['store', 'destroy']);
    Route::resource('deliveries', 'Admin\DeliveryController')->except(['show']);
    Route::resource('orders', 'Admin\OrderController')->except(['create', 'store']);
    Route::resource('comments', 'Admin\CommentController')->except(['create']);
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\DataTables\RoleDataTable;

class RoleController extends Controller
{
    public function __construct()
    {
      $this->middleware('permission:role-list');
      $this->middleware('permission:role-create', ['only' => ['create','store']]);
      $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
      $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(RoleDataTable $dataTable)
    {
        return $dataTable->render('admin.roles.index');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create',[
          'permissions' => Permission::get()
        ]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permissions' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permissions'));

        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('admin.roles.show',[
          'role' => $role,
          'rolePermissions' => $role->permissions()->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('admin.roles.edit', [
          'role' => $role,
          'permissions' => Permission::all(),
          'selectedPermissions' => $role->permissions()->pluck('id', 'name')->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request, [
            'name' => 'required',
            'permissions' => 'required',
        ]);

        $role->update([
          'name' => $request->input('name')
        ]);
        $role->syncPermissions($request->input('permissions'));
        $role->save();

        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

resources/views/admin/roles/__action.blade.php
<div class="form-group mb-0" role="group">
  <a class="btn btn-success" href="{{ route('roles.show', $model->id)}}" role="button">Show</a>
  @can('role-edit')
  <a class="btn btn-primary" href="{{ route('roles.edit', $model->id)}}" role="button">Edit</a>
  @endcan
  @can('role-delete')
  <form method="POST" action="{{ route('roles.destroy', $model->id)}}" accept-charset="UTF-8" style="display:inline">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
  @endcan
</div>

resources/views/admin/roles/__form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            <input placeholder="Name" class="form-control" name="name" type="text" value="{{$role->name ?? ''}}">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class='form-group'>
        <label>Permissions:</label>
        <select class="form-control permissions" multiple="multiple"  name="permissions[]" data-placeholder="Select a permissions" style="width: 100%;" tabindex="-1" aria-hidden="true">
          @foreach ($permissions as $permission)
            <option value="{{$permission->id}}" @if( Route::current()->getName() == 'roles.edit' ) {{in_array($permission->id, $selectedPermissions)?'selected':''}} @endif>{{$permission->name}}</option>
          @endforeach
        </select>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button class="btn btn-primary" type="submit">Save</button>
    </div>
</div>

resources/views/admin/roles/create.blade.php
@extends('adminlte::page')
@section('title', 'Roles')

@section('content_header')
    <h1>Roles Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Create role</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('roles.store')}}" method="post">
      @csrf
      @include('admin.roles.__form')
    </form>
  </div>
</div>


@stop

@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('.permissions').select2();
  });
</script>
@stop

resources/views/admin/roles/edit.blade.php
@extends('adminlte::page')
@section('title', 'Roles')

@section('content_header')
    <h1>Roles Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Edit role</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('roles.update', $role->id)}}" method="post">
      @csrf
      @method('PUT')
      @include('admin.roles.__form')
    </form>
  </div>
</div>


@stop
@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('.permissions').select2();
  });
</script>
@stop

resources/views/admin/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
    <h1>Roles Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">All roles</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('roles.create')}}" class="btn btn-primary">Create</a>
    </div>
  </div>
  <div class="box-body">
    @include('messages.list')
    {!! $dataTable->table() !!}
  </div>
</div>
@stop

@section('js')
{!! $dataTable->scripts() !!}
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="/vendor/datatables/buttons.server-side.js"></script>
@stop

resources/views/admin/roles/show.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
    <h1>Roles Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">{{ $role->name }} Role</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
    </div>
  </div>

  <div class="box-body">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $role->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Permissions:</strong>
                @if(!empty($rolePermissions))
                    @foreach($rolePermissions as $permission)
                        <label class="badge badge-success">{{ $permission->name }}</label>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
  </div>

</div>
@stop