routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('test');

Route::post('/cart/add', 'CartController@create')->name('cart.add');
Route::patch('/cart/update/{id}', 'CartController@update')->name('cart.update');
Route::delete('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart', 'CartController@show')->name('cart.index');

Route::get('/checkout', 'CheckoutController@index')->name('checkout');
Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

Route::get('/p/{slug}', 'ProductController@show');
Route::get('/c/{slug?}', 'CategoryController@show')->name('category.menu');

Route::post('/r/comments', 'CommentController@store')->name('comments.store');

Route::middleware('auth')->group(function () {
    Route::get('/u/profile', 'UserController@edit');
    Route::patch('/u/profile', 'UserController@update')->name('user.update');
});

Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin.index');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions', 'Admin\PermissionController')->except(['show']);
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController')->except(['show']);
    Route::resource('products', 'Admin\ProductController');
    Route::resource('download', 'Admin\DownloadController')->only(['store', 'destroy']);
    Route::resource('deliveries', 'Admin\DeliveryController')->except(['show']);
    Route::resource('orders', 'Admin\OrderController')->except(['create', 'store']);
    Route::resource('comments', 'Admin\CommentController')->except(['create']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function profiles()
    {
      return $this->hasOne('App\Profile');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\UserDataTable;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
      $this->middleware('permission:user-list');
      $this->middleware('permission:user-create', ['only' => ['create','store']]);
      $this->middleware('permission:user-edit', ['only' => ['edit','update']]);
      $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserDataTable $datatable)
    {
        return $datatable->render('admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', [
          'roles' => Role::get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed',
            'roles' => 'required'
        ]);

        $request['password'] = Hash::make($request['password']);

        $user = User::create($request->only('name', 'email','password'));
        $user->assignRole($request->input('roles'));

        return redirect()->route('users.index')
                       ->with('success','User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function show($id)
    // {
    //    $user = User::find($id);
    //    return view('admin.users.show',compact('user'));
    // }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
       return view('admin.users.edit',[
         'user'=> $user,
         'roles' => Role::get(),
         'userRoles' => $user->roles()->pluck('id', 'name')->toArray()
       ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
       $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'confirmed',
            'roles' => 'required'
       ]);

       if(!empty($request['password'])){
           $request['password'] = Hash::make($request['password']);
       }else{
           $request = array_except($request,array('password'));
       }

       if (isset($request['roles'])) {
            $user->roles()->sync($request['roles']);
        }
        else {
            $user->roles()->detach();
        }

        $user->update($request->all());

       return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
       $user->delete();
       return redirect()->route('users.index')
                      ->with('success','User deleted successfully');
    }
}

resources/views/admin/users/__action.blade.php
<div class="form-group" role="group">
  <a class="btn btn-success" href="{{ route('users.show', $model->id)}}" role="button">Show</a>
  @can('user-edit')
  <a class="btn btn-primary" href="{{ route('users.edit', $model->id)}}" role="button">Edit</a>
  @endcan
  @can('user-delete')
  <form method="POST" action="{{ route('users.destroy', $model->id)}}" accept-charset="UTF-8" style="display:inline">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
  @endcan
</div>

resources/views/admin/users/__form.blade.php
<div class="form-group">
  <label for="name">Name</label>
  <input class="form-control" name="name" type="text" value="{{$user->name ?? ''}}" id="name">
</div>
<div class="form-group">
  <label for="email">Email</label>
  <input class="form-control" name="email" type="email" value="{{$user->email ?? ''}}" id="email">
</div>
<div class='form-group'>
  <label>Roles</label>
  <select class="form-control user-roles" name="roles[]" multiple="multiple" data-placeholder="Select a user roles" style="width: 100%;" tabindex="-1" aria-hidden="true">
    @foreach ($roles as $role)
        <option value="{{$role->id}}" @if( Route::current()->getName() == 'users.edit' ) {{in_array($role->id, $userRoles)?'selected':''}} @endif>{{$role->name}}</option>
    @endforeach
  </select>
</div>
<div class="form-group">
  <label for="password">Password</label><br>
  <input class="form-control" name="password" type="password" value="" id="password">
</div>
<div class="form-group">
  <label for="password">Confirm Password</label><br>
  <input class="form-control" name="password_confirmation" type="password" value="">
</div>

<input class="btn btn-primary" type="submit" value="Save">

resources/views/admin/users/create.blade.php
@extends('adminlte::page')
@section('title', 'Users')

@section('content_header')
    <h1>Users Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Create user</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('users.store')}}" method="post">
      @csrf
      @include('admin.users.__form')
    </form>
  </div>
</div>


@stop

@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('.user-roles').select2();
  });
</script>
@stop

resources/views/admin/users/edit.blade.php
@extends('adminlte::page')
@section('title', 'Users')

@section('content_header')
    <h1>Users Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Edit user</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('users.update', $user)}}" method="post">
      @csrf
      @method('PUT')
      @include('admin.users.__form')
    </form>
  </div>
</div>


@stop
@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('.user-roles').select2();
  });
</script>
@stop

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">All users</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('users.create')}}" class="btn btn-primary">Create</a>
    </div>
  </div>
  <div class="box-body">
    @include('messages.list')
    {!! $dataTable->table() !!}

  </div>
</div>
@stop

@section('js')
{!! $dataTable->scripts() !!}
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="/vendor/datatables/buttons.server-side.js"></script>
@stop