routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('test');

Route::post('/cart/add', 'CartController@create')->name('cart.add');
Route::patch('/cart/update/{id}', 'CartController@update')->name('cart.update');
Route::delete('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart', 'CartController@show')->name('cart.index');

Route::get('/checkout', 'CheckoutController@index')->name('checkout');
Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

Route::get('/p/{slug}', 'ProductController@show');
Route::get('/c/{slug?}', 'CategoryController@show')->name('category.menu');

Route::post('/r/comments', 'CommentController@store')->name('comments.store');

Route::middleware('auth')->group(function () {
    Route::get('/u/profile', 'UserController@edit');
    Route::patch('/u/profile', 'UserController@update')->name('user.update');
});

Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin.index');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions', 'Admin\PermissionController')->except(['show']);
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController')->except(['show']);
    Route::resource('products', 'Admin\ProductController');
    Route::resource('download', 'Admin\DownloadController')->only(['store', 'destroy']);
    Route::resource('deliveries', 'Admin\DeliveryController')->except(['show']);
    Route::resource('orders', 'Admin\OrderController')->except(['create', 'store']);
    Route::resource('comments', 'Admin\CommentController')->except(['create']);
});

app/Category.php
<?php

namespace App;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasSlug;
    protected $fillable = ['name', 'parent_id', 'slug'];

    public function products()
    {
      return $this->belongsToMany('App\Product');
    }

    public function children()
    {
      return $this->hasMany(self::class, 'parent_id');
    }

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\DataTables\CategoryDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
      $this->middleware('permission:categories-list');
      $this->middleware('permission:categories-create', ['only' => ['create','store']]);
      $this->middleware('permission:categories-edit', ['only' => ['edit','update']]);
      $this->middleware('permission:categories-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CategoryDataTable $dataTable)
    {
      return $dataTable->render('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.categories.create', [
        'category' => [],
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter' => ''
      ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|unique:categories'
        ]);

        Category::create($request->all());

        return redirect()->route('categories.index')
                        ->with('success','Category created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
      return view('admin.categories.edit', [
        'category' => $category ,
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter' => ''
      ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('categories.index')
                        ->with('success','Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index')
                        ->with('success','Category deleted successfully');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function show($slug)
    {
        $category = Category::with('products')->where('slug', $slug)->firstOrFail();
        $products = $category->products()->paginate(20);

        return view('front.categories.index', [
          'category' => $category,
          'products' => $products
        ]);
    }
}

resources/views/admin/categories/__action.blade.php
<div class="form-group mb-0" role="group">
  @can('categories-edit')
  <a class="btn btn-primary" href="{{ route('categories.edit', $model->id)}}" role="button">Edit</a>
  @endcan
  @can('categories-delete')
  <form method="POST" action="{{ route('categories.destroy', $model->id)}}" accept-charset="UTF-8" style="display:inline">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
  @endcan
</div>

resources/views/admin/categories/__categories.blade.php
@foreach($categories as $categoryItem)
  <option value="{{$categoryItem->id ?? ''}}"
    @isset($category->id)
      @if ($category->parent_id == $categoryItem->id)
        selected
      @endif
      @if ($category->id == $categoryItem->id)
        disabled=""
      @endif
    @endisset
  >
  {{ $delimiter ?? '' }} {{ $categoryItem->name ?? '' }}
</option>

  @isset($categoryItem->children)
    @include('admin.categories.__categories', [
      'categories' => $categoryItem->children,
      'delimiter' => ' - ' . $delimiter
    ])
  @endisset
@endforeach

resources/views/admin/categories/__form.blade.php
<div class="form-group">
  <label for="name">Name:</label>
  <input type="text" class="form-control" name="name" value="{{$category->name ?? ''}}" placeholder="Enter a name">
</div>
<div class="form-group">
  <label for="parent_id">Parent:</label>
  <select class="form-control" name="parent_id">
    <option value="0">-- Without parent --</option>
    @include('admin.categories.__categories')
  </select>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 text-center">
    <button class="btn btn-primary" type="submit">Save</button>
</div>

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')
@section('title', 'Categories')

@section('content_header')
    <h1>Categories Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Create category</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('categories.store')}}" method="post">
      @csrf
      @include('admin.categories.__form')
    </form>
  </div>
</div>


@stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')
@section('title', 'Categories')

@section('content_header')
    <h1>Categories Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Edit category</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('categories.update', $category)}}" method="post">
      @csrf
      @method('PUT')
      @include('admin.categories.__form')
    </form>
  </div>
</div>


@stop

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Categoeies')

@section('content_header')
    <h1>Categories Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">All categories</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('categories.create')}}" class="btn btn-primary">Create</a>
    </div>
  </div>
  <div class="box-body">
    @include('messages.list')

    {!! $dataTable->table() !!}

  </div>
</div>
@stop

@section('js')
{!! $dataTable->scripts() !!}
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="/vendor/datatables/buttons.server-side.js"></script>
@stop