routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('test');

Route::post('/cart/add', 'CartController@create')->name('cart.add');
Route::patch('/cart/update/{id}', 'CartController@update')->name('cart.update');
Route::delete('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart', 'CartController@show')->name('cart.index');

Route::get('/checkout', 'CheckoutController@index')->name('checkout');
Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');

Route::get('/p/{slug}', 'ProductController@show');
Route::get('/c/{slug?}', 'CategoryController@show')->name('category.menu');

Route::post('/r/comments', 'CommentController@store')->name('comments.store');

Route::middleware('auth')->group(function () {
    Route::get('/u/profile', 'UserController@edit');
    Route::patch('/u/profile', 'UserController@update')->name('user.update');
});

Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin.index');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions', 'Admin\PermissionController')->except(['show']);
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController')->except(['show']);
    Route::resource('products', 'Admin\ProductController');
    Route::resource('download', 'Admin\DownloadController')->only(['store', 'destroy']);
    Route::resource('deliveries', 'Admin\DeliveryController')->except(['show']);
    Route::resource('orders', 'Admin\OrderController')->except(['create', 'store']);
    Route::resource('comments', 'Admin\CommentController')->except(['create']);
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use App\DataTables\PermissionDataTable;

class PermissionController extends Controller
{
  public function __construct()
  {
    $this->middleware('permission:permission-list');
    $this->middleware('permission:permission-create', ['only' => ['create','store']]);
    $this->middleware('permission:permission-edit', ['only' => ['edit','update']]);
    $this->middleware('permission:permission-delete', ['only' => ['destroy']]);
  }

  public function index(PermissionDataTable $dataTable)
  {
    return $dataTable->render('admin.permissions.index');
  }

  public function create()
  {
    return view('admin.permissions.create');
  }

  public function store(Request $request)
  {
    $this->validate($request, [
            'name'=>'required|unique:permissions,name',
        ]);

    Permission::create(['name' => $request->input('name')]);

    return redirect()->route('permissions.index')
                    ->with('success','Permission created successfully');
  }

  public function edit(Permission $permission)
  {
    return view('admin.permissions.edit',[
      'permission' => $permission
    ]);
  }

  public function update(Request $request, Permission $permission)
  {
    $this->validate($request, [
            'name'=>'required|unique:permissions,name',
        ]);

    $permission->update(['name' => $request->input('name')]);
    $permission->save();

    return redirect()->route('permissions.index')
                    ->with('success', 'Permission updated successfully');
  }

  public function destroy(Permission $permission)
  {
    $permission->delete();
    return redirect()->route('permissions.index')
                    ->with('success','Permission deleted successfully');
  }

}

resources/views/admin/permissions/__action.blade.php
<div class="form-group mb-0" role="group">
  @can('permission-edit')
  <a class="btn btn-primary" href="{{ route('permissions.edit', $model->id)}}" role="button">Edit</a>
  @endcan
  @can('permission-delete')
  <form method="POST" action="{{ route('permissions.destroy', $model->id)}}" accept-charset="UTF-8" style="display:inline">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
  @endcan
</div>

resources/views/admin/permissions/__form.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input name="name" type="text" value="{{$permission->name ?? ''}}" id="name" class="form-control">
</div>

<div class="col-xs-12 col-sm-12 col-md-12 text-center">
    <button class="btn btn-primary" type="submit">Save</button>
</div>

resources/views/admin/permissions/create.blade.php
@extends('adminlte::page')

@section('title', 'Permissions')

@section('content_header')
    <h1>Permissions Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Create permission</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('permissions.index')}}" class="btn btn-primary">Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('permissions.store')}}" method="post">
      @csrf
      @include('admin.permissions.__form')
    </form>

  </div>
</div>
@stop

resources/views/admin/permissions/edit.blade.php
@extends('adminlte::page')

@section('title', 'Permissions')

@section('content_header')
    <h1>Permissions Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">Edit permission</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('permissions.index')}}" class="btn btn-primary">Back</a>
    </div>
  </div>
  <div class="box-body">
    @include('errors.list')
    <form action="{{route('permissions.update', $permission->id)}}" method="post">
      @csrf
      @method('PUT')
      @include('admin.permissions.__form')
    </form>
  </div>
</div>
@stop

resources/views/admin/permissions/index.blade.php
@extends('adminlte::page')

@section('title', 'Permissions')

@section('content_header')
    <h1>Permissions Management</h1>
@stop

@section('content')
<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
        <h3 class="box-title">All permissions</h3>
    </div>
    <div class="pull-right">
      <a href="{{route('permissions.create')}}" class="btn btn-primary">Create</a>
    </div>
  </div>
  <div class="box-body">
    @include('messages.list')
    {!! $dataTable->table() !!}

  </div>
</div>

<div class="modal fade" id="ajaxModel" aria-hidden="true">
 <div class="modal-dialog">
     <div class="modal-content">
         <div class="modal-header">
             <h4 class="modal-title" id="modelHeading"></h4>
         </div>
         <div class="modal-body">
             <form id="productForm" name="productForm" class="form-horizontal">
                <input type="hidden" name="product_id" id="product_id">
                 <div class="form-group">
                     <label for="name" class="col-sm-2 control-label">Name</label>
                     <div class="col-sm-12">
                         <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" value="" maxlength="50" required="">
                     </div>
                 </div>

                 <div class="form-group">
                     <label class="col-sm-2 control-label">Details</label>
                     <div class="col-sm-12">
                         <textarea id="detail" name="detail" required="" placeholder="Enter Details" class="form-control"></textarea>
                     </div>
                 </div>

                 <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                  </button>
                 </div>
             </form>
         </div>
     </div>
 </div>
</div>
@stop

@section('js')
{!! $dataTable->scripts() !!}
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="/vendor/datatables/buttons.server-side.js"></script>
<script type="text/javascript">

$(document).on('click', '.delete', function(){
        var id = $(this).attr('id');
        if(confirm("Are you sure you want to Delete this data?"))
        {
            $.ajax({
                url:"/permissions/destroy",
                mehtod:"get",
                data:{id:id},
                success:function(data)
                {
                    alert(data);
                    $('#student_table').DataTable().ajax.reload();
                }
            })
        }
        else
        {
            return false;
        }
    });


</script>
@stop